Algoritmo "parouimpar"
// Disciplina   : PA
// Professor   : Cintia Pinho
// Descrição   : Descobrir se o valor é par ou ímpar
// Autor(a)    : Stephanie Mota
// Data atual  : 26/07/2022
Var
num: inteiro


Inicio

escreval ("Digite o número")
leia (num)


se (num mod 2=0) entao
    escreval ("O número é par")
    
senao
    escreval ("O número é ímpar")

fimse


Fimalgoritmo