Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Escreva um número que imprima a tabuada
// Autor(a)    : Stephanie Mota
// Data atual  : 06/09/2022
Var
num, cont, resul: inteiro


Inicio
escreval ("Qual é o número que você deseja multiplicar?")
leia(num)

para cont de 0 ate 10 faca

    resul <- num*cont
    escreval (num,"X", cont, " = ", resul)
fimpara


Fimalgoritmo